apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scoreboard-db
  name: scoreboard-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scoreboard-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: scoreboard-db
    spec:
      containers:
        - image: redis:5.0.2-alpine
          name: scoreboard-db
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
