# Declare variables to be passed into your templates.
name: monero

ports:
  p2pPort: 18080
  p2pNodePort: 30680
  rpcPort: 18081
  rpcNodePort: 30681

nfs:
  address: 192.168.0.34
  mountPoint: /media/drive/nfs/monero

images:
  daemon:
    registry: docker.io
    repository: romanmc72
    name: monero-daemon
    tag: 1.0.1
  miner:
    registry: docker.io
    repository: romanmc72
    name: monero-miner
    tag: 1.0.1

daemon:
  blockchain_directory: /home/monerod
  name: monerod

miner:
  replicas: 10
  name: xmrig
